Repository ORNL/zambeze, pull requests merged in 2023-01, with the labels that each got.

#88 Integration test using docker compose
  .github/workflows/rsync-example.yml
  deployment/Dockerfile
  deployment/compose.yml
  examples/__init__.py
  examples/imagemagick-files.py
  requirements.txt
  setup.cfg
  tests/test_imagemagick_files.py
Labels: DevOps: CI

#86 Rabbitmq to Devel
  examples/imagemagick-files.py
  requirements.txt
  tests/test_activity_shell.py
  tests/test_campaign.py
  tests/test_imagemagick_files.py
  tests/test_message_activity_validator.py
  tests/test_plugin_shell.py
  tests/test_plugins.py
  tests/test_queue_factory.py
  tests/test_queue_nats.py
  zambeze/campaign/activities/shell.py
  zambeze/campaign/campaign.py
  zambeze/config.py
  zambeze/orchestration/agent/agent.py
  zambeze/orchestration/agent/message_handler.py
  zambeze/orchestration/agent/temp_activity_to_plugin_map.py
  zambeze/orchestration/executor.py
  zambeze/orchestration/identity.py
  zambeze/orchestration/message/activity_message/message_activity_template_generator.py
  zambeze/orchestration/message/activity_message/message_activity_validator.py
  zambeze/orchestration/message/message_factory.py
  zambeze/orchestration/message/status_message/message_status_validator.py
  zambeze/orchestration/message/transfer_hippo.py
  zambeze/orchestration/plugin_modules/git/git_message_validator.py
  zambeze/orchestration/plugin_modules/globus/globus_common.py
  zambeze/orchestration/plugin_modules/globus/globus_message_validator.py
  zambeze/orchestration/plugin_modules/globus/globus_uri_separator.py
  zambeze/orchestration/plugin_modules/shell/shell.py
  zambeze/orchestration/plugins.py
  zambeze/orchestration/processor.py
  zambeze/orchestration/queue/abstract_queue.py
  zambeze/orchestration/queue/queue_factory.py
  zambeze/orchestration/queue/queue_nats.py
  zambeze/orchestration/queue/queue_rmq.py
  zambeze/settings.py
Labels: enhancement

#92 Remove call to non existent settings object
  zambeze/orchestration/queue/queue_nats.py
Labels: Priority: High

#91 Joshua s brown pyre cleanup
  .github/workflows/pyre-check.yml
  tests/test_message_factory.py
  tests/test_queue_factory.py
  zambeze/campaign/activities/shell.py
  zambeze/orchestration/agent/commands.py
  zambeze/orchestration/message/abstract_message.py
  zambeze/orchestration/message/activity_message/message_activity_validator.py
  zambeze/orchestration/message/message_factory.py
  zambeze/orchestration/message/status_message/message_status_validator.py
  zambeze/orchestration/plugin_modules/globus/globus.py
  zambeze/orchestration/plugin_modules/rsync/rsync_message_validator.py
  zambeze/orchestration/plugins.py
  zambeze/orchestration/queue/queue_factory.py
  zambeze/orchestration/queue/queue_nats.py
  zambeze/orchestration/queue/queue_rmq.py
Labels: Priority: Low, Technical Debt: Type Consistency

#94 Separate format and unit testing into different actions
  .github/workflows/format-check.yml
  .github/workflows/unit-tests.yml
Labels: Priority: Low

#95 Change name from build to type-check
  .github/workflows/pyre-check.yml
Labels: Priority: Low

#90 rabbitmq integration tests (into devel)
  .github/workflows/shell-activity-example.yml
  deployment/README.md
  deployment/compose-nats.yml
  deployment/compose-rabbit.yml
  examples/imagemagick-files.py
  examples/imagemagick_files.py
  tests/test_imagemagick_files.py
  zambeze/campaign/campaign.py
  zambeze/orchestration/executor.py
  zambeze/orchestration/queue/queue_rmq.py
  zambeze/settings.py
Labels: Priority: High

#93 Attempt to apply formatting fixes
  .github/workflows/format-check.yml
  examples/imagemagick_files.py
  setup.cfg
  tests/test_imagemagick_files.py
  tests/test_plugin_shell.py
  zambeze/campaign/activities/shell.py
  zambeze/orchestration/agent/message_handler.py
  zambeze/orchestration/executor.py
  zambeze/orchestration/message/message_factory.py
  zambeze/orchestration/message/transfer_hippo.py
  zambeze/orchestration/plugins.py
  zambeze/orchestration/queue/queue_factory.py
  zambeze/orchestration/queue/queue_nats.py
  zambeze/orchestration/queue/queue_rmq.py
Labels: Priority: Low

#100 Add Developer document
  CONTRIBUTING.md
Labels: documentation
